import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopHeader, { Header } from "../Components/TopHeader";
import Footer from "../Components/Footer";
import Navbar from "../Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
         <TopHeader/>
         <Header/>
         <Navbar/>
        {children}
        <Footer/>
        </body>
      
    </html>
  );
}
